services:
  cinepick-server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      cinepick_rf-db:
        condition: service_healthy


  cinepick_rf-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinepick_rf
    volumes:
      - ~/cinepick/docker_mysql_data:/var/lib/mysqldocker rm -f cinepick-cinepick_rf-db-1
      - ~/cinepick/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      retries: 10
      start_period: 20s
